### ISSUE TITLE
Error: V1.5.8 Compilation failed - Error: For EraVM, only the ZKsync fork of `solc` can be used

### ISSUE THREAD

**Issue by homeyong** [matter-labs/era-compiler-solidity#230]
🐛 Bug Report
Error: V1.5.8 Compilation failed - Error: For EraVM, only the ZKsync fork of `solc` can be used

📝 Description
When working with zkSolc 1.5.8, there is the above error for my given standard-json input.

🔄 Reproduction Steps
```
{
  "language": "Solidity",
  "sources": {
    "src/Counter.sol": {
      "content": "// SPDX-License-Identifier: UNLICENSED\npragma solidity ^0.8.13;\n\ncontract Counter {\n    uint256 public number;\n\n    function setNumber(uint256 newNumber) public {\n        number = newNumber;\n    }\n\n    function increment() public {\n        number++;\n    }\n}\n"
    }
  },
  "settings": {
    "viaIR": false,
    "codegen": "yul",
    "remappings": [
      "forge-std/=lib/forge-std/src/"
    ],
    "evmVersion": "cancun",
    "outputSelection": {
      "*": {
        "*": [
          "abi"
        ]
      }
    },
    "optimizer": {
      "enabled": true,
      "runs": 200
    },
    "metadata": {},
    "libraries": {}
  }
}
```
Use the above input.json with zksolc-windows-amd64-gnu-v1.5.8.exe retrieved from this link https://github.com/matter-labs/zksolc-bin/releases and and also use solc 0.8.28.

Sample command:
zksolc-1-5-8.exe --solc "C:\yourpath\solc-0-8-28.exe" --standard-json "C:\yourpath\zksync\contracts\test-input.json" > "C:\yourpath\zksync\contracts\test-output-error.json"

🤔 Expected Behavior
Produce the output.json accordingly

😯 Current Behavior
test-output-error.json returns this content:

{"errors":[{"component":"general","formattedMessage":"Error: For EraVM, only the ZKsync fork of `solc` can be used: `C:\\solcExe\\solc-windows-amd64-v0.8.28+commit.7893614a.exe` ZKsync revision parsing: missing line..\n","message":"For EraVM, only the ZKsync fork of `solc` can be used: `C:\\solcExe\\solc-windows-amd64-v0.8.28+commit.7893614a.exe` ZKsync revision parsing: missing line..","severity":"error","type":"Error"}],"zk_version":"1.5.8"}

🖥️ Environment
Uses zksolc1.5.8 + solc0.8.28 windows .exe binary

📋 Additional Context
This error is not reproducible when using zksolc1.5.7. In this version, there is no issue in producing the output.json.

**Comment by hedgar2017** [comment]
Hey @homeyong!
Please download [solc](https://github.com/matter-labs/era-solidity/releases) from here. The upstream one cannot be used with *zksolc*.

**Comment by homeyong** [comment]
hey @hedgar2017, 

May I know the enforce to use ZK edition of solc start enforcing from version v1.5.8 onwards?

**Comment by hedgar2017** [comment]
> hey @hedgar2017, 
> 
> 
> 
> May I know the enforce to use ZK edition of solc start enforcing from version v1.5.8 onwards?

Yes, enforcing makes total sense!
There is no need to use the original one for EraVM?
Please make sure you're using the latest revision (1.0.1).
