### ISSUE TITLE
Error: V1.5.9 And V1.5.10 Compilation failed - Error: ZKsync revision parsing: missing revision

### ISSUE THREAD

**Issue by homeyong** [matter-labs/era-compiler-solidity#255]
🐛 Bug Report
Error: V1.5.9 And V1.5.10 Compilation failed - Error: ZKsync revision parsing: missing revision.

📝 Description
When working with zkSolc  V1.5.9 And V1.5.10, there is the above error for my given standard-json input.

🔄 Reproduction Steps
```
{
  "language": "Solidity",
  "sources": {
    "src/Counter.sol": {
      "content": "// SPDX-License-Identifier: UNLICENSED\npragma solidity ^0.8.13;\n\ncontract Counter {\n    uint256 public number;\n\n    function setNumber(uint256 newNumber) public {\n        number = newNumber;\n    }\n\n    function increment() public {\n        number++;\n    }\n}\n"
    }
  },
  "settings": {
    "viaIR": false,
    "codegen": "yul",
    "remappings": [
      "forge-std/=lib/forge-std/src/"
    ],
    "evmVersion": "cancun",
    "outputSelection": {
      "*": {
        "*": [
          "abi"
        ]
      }
    },
    "optimizer": {
      "enabled": true,
      "runs": 200
    },
    "metadata": {},
    "libraries": {}
  }
}
```

Use the above input.json with zksolc-windows-amd64-gnu-v1.5.9.exe & zksolc-windows-amd64-gnu-v1.5.10.exe retrieved from this link (https://github.com/matter-labs/zksolc-bin/releases) and also use solc (zk fork) - solc-windows-amd64-0.8.24-1.0.1.exe from (https://github.com/matter-labs/era-solidity)

Sample command:
zksolc-windows-amd64-gnu-v1.5.10.exe --solc "C:\solcExe\zksync\solc-windows-amd64-0.8.24-1.0.1.exe" --standard-json < zksync_test_version.json > result_test_version.json

🤔 Expected Behavior
Produce the output.json accordingly

😯 Current Behavior
test-output-error.json returns this content:

{"errors":[{"component":"general","formattedMessage":"Error: For EraVM, only the ZKsync fork of `solc` can be used: `C:\\solcExe\\zksync\\solc-windows-amd64-0.8.24-1.0.1.exe` ZKsync revision parsing: missing revision.\n","message":"For EraVM, only the ZKsync fork of `solc` can be used: `C:\\solcExe\\zksync\\solc-windows-amd64-0.8.24-1.0.1.exe` ZKsync revision parsing: missing revision.","severity":"error","type":"Error"}],"zk_version":"1.5.10"}

🖥️ Environment
Uses zksolc1.5.10 + solc-windows-amd64-0.8.24-1.0.1.exe windows .exe binary

📋 Additional Context
This error is not reproducible when using zksolc1.5.7. In this version, there is no issue in producing the output.json.

**Comment by homeyong** [comment]
Based on what being noticed, the --version for the solc (zkfork), started to change where version 0.8.27 onwards:
from: ZKsync: 1.0.1 to ZKsync: 0.8.28-1.0.1.

Can refer to the screenshot below:
![Image](https://github.com/user-attachments/assets/6b4c7e91-c5a7-459f-9117-eda8d474ef02)

**Comment by homeyong** [comment]
I can see from latest sourcecode, it is looking for the "-". 
This inconsistency causing issue when we are using latest version of zksolc and compile lower version of solc. 
![Image](https://github.com/user-attachments/assets/f25c19f4-9378-45b6-88d0-c6b34d736fea)

**Comment by homeyong** [comment]
hi @uF4No, 

Thanks a lots, it worked now.
